
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/"
    command: ["catalina.sh", "run"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

